# Brew Config Files

brew "awscli"
brew "cocoapods"
brew "neovim"
brew "nvm"
brew "watchman"
brew "typescript"
brew "yarn"
brew "gpg"
brew "ripgrep"
brew "ruby"
brew "tree"
tap "aws/tap"
brew "aws-sam-cli"
brew "tap hashicorp/tap"
brew "hashicorp/tap/terraform"
